### ISSUE TITLE
Feature List

### ISSUE THREAD

**Issue by NathanBland** [NathanBland/Sprout#2]
This issues is to serve as the list of features that should be implemented in this application.
The initial list is as follows:
- user authentication
- teacher/admin interface
- progress through lessons (i.e. 1/3 of the way through lesson 2)
- embedded videos in lessons
- lesson file uploads (ppt, doc, etc)

**Comment by Malachi-M** [comment]
These proposed features look great. Lets take a look at a few current sites that provide a similar service.
- [Team Treehouse](http://teamtreehouse.com/)
- [Code School](https://www.codeschool.com/)
- [Code Academy](http://www.codecademy.com/)
- [Code.org](http://code.org/learn)
- [Pluralsight](http://www.pluralsight.com/)

I understand that none of these institutions are taking the same angle at education that we would be as we are still within an institution. That said, the various ideas on layout and presentation of material may prove beneficial.

**Comment by NathanBland** [comment]
I like the way that [code school](https://www.codeschool.com/paths) lays out their options for paths. Seems similar to what we could do for courses and then lessons inside of those. Thoughts?

Also it is worth pointing out that all of these websites have one area of focus, that being coding. While they do have separate specialties it would be wise of us to keep in mind we are working on a bit of a grander scope.

**Comment by Malachi-M** [comment]
That is a very excellent point about the commonality of focus for these sites. I do like how they layout their paths. Lets check out a few more sites:

##### Online Course Programs
- [Khan Academy](https://www.khanacademy.org/)
- [Udemy](https://www.udemy.com/courses/)
- [Lynda](www.lynda.com/)

##### Online Customizable Course Platforms
- [Academy Of Mine](http://academyofmine.com/demo1/)
- [Digital Chalk](http://www.digitalchalk.com/)
- [ProProfs - Flash cards](http://www.proprofs.com/flashcards/)
  - Such a feature might be interesting.
    I list these to look for aspects that draw our attention in layout, routing, feature sets.
