### ISSUE TITLE
Data Schema

### ISSUE THREAD

**Issue by NathanBland** [NathanBland/Sprout#3]
We need to define data schema for the following objects at minimum.

**User**
- isteacher ? (perhaps should be separate schema)
- InstitutionId
- [classes]
- other?

**Lesson**
- classId (or should lessons be a sub-array of class?)
- title - required
- description text (brief summary of lesson) - optional
- body  (main content section) - required
- [materials] uploaded files - optional

**Class**
- title
- description
- course code
- [pre-reqs]
- registration code ? (for classes that aren't open enrollment, not sure if this is needed or not)
- administratorId (better way to do this?)
- institutionId (better way to do this?)

**Institution**
- name
- managerId
- contact info
- class list ? (or we could just pull from the classes where the institutionId was the same... Not sure)
- Other?

This is by no means an exhaustive list, and is mostly what I could think of off of the top of my head.
Please post editions/revisions and I'll try to include them in this.

**Comment by Malachi-M** [comment]
I would recommend that for the User group an additional attribute of "isWithdrawn" or something similar to allow for a student to withdraw from a course.

**Comment by NathanBland** [comment]
Would we want to show them as withdrawn, or would we just remove them from the course?

**Comment by Malachi-M** [comment]
For reporting purposes. Either withdrawn or removed.

**Comment by NathanBland** [comment]
Everything has changed vastly from this...Closing.
